### ISSUE TITLE
request for icon data

### ISSUE THREAD

**Issue by ebenezerguenou** [capps096github/cupertino_icons_gallery#3]

**Comment by capps096github** [comment]
Hello @ebenezerguenou, this repository and codebase do not provide access to the Icon Data needed to build your cross-platform icons and emojis set. 

This is because the repo is built on top of the [cupertino_icons](https://pub.dev/packages/cupertino_icons) package for Flutter which [under the hood uses the Cupertino Icons Font](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html) that provides all the Icon Data required for rendering these icons in Flutter apps, therefore if you are looking for such `Icon Data` then this is not the go-to solution for that. 

So, therefore, I will be closing this issue since it seems to be a design-related issue rather than a technical one related to the code base used in this repo.
